In [1]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('data.csv')
dataset.head()

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570

<H2>QUESTION 1 </H2>

In [9]:
A = [1,2,3,4,5,6]
B = [13, 21, 34]
A.extend(B)
print(A)
A.append(B)
print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 34]
[1, 2, 3, 4, 5, 6, 13, 21, 34, [13, 21, 34]]


<H2>QUESTION 2 </H2>

In [12]:
print(np.identity(3),'\n')
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<H2>QUESTION 3 </H2>

In [36]:
contents = dataset.iloc[:,4].unique()
result = {}
for content in contents:
    con = dataset.iloc[:,4]== content
    avg = dataset[con].iloc[:,8].mean()
    result[content]=avg

result

{'coal': 67.42182999883,
 'gas': 13.659396569737071,
 'nuclear': 4955.157002444988,
 'oil': 168.87708568948415,
 'waste': 19.518122448979593,
 'other': 18.253856287425148}

<H2>QUESTION 4 </H2>

In [42]:
dataset.iloc[:,7].describe()

count    29523.000000
mean         8.492111
std         10.600220
min          0.000001
25%          1.024000
50%          5.762694
75%         17.006000
max        341.260000
Name: fuel_mmbtu_per_unit, dtype: float64

<H2>QUESTION 5 </H2>

In [44]:
skew_value = dataset.iloc[:,6].skew()
kurt_value = dataset.iloc[:,6].kurt()

print('Skew: %.3f and Kurt: %.3f'%(skew_value, kurt_value))

Skew: 15.851 and Kurt: 651.369


<H2>QUESTION 6 </H2>

In [45]:
dataset.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [53]:
missing_feature_column = dataset.columns[5]
total_numbers = len(dataset.iloc[:,5])
missing_numbers = 180 
per = (missing_numbers/total_numbers)
per = per * 100
print('Feature: %s, Total: %d, Percent: %.3f'%(missing_feature_column , missing_numbers, per))

Feature: fuel_unit, Total: 180, Percent: 0.610


<H2>QUESTION 7 </H2>

In [85]:
print('CATEGORICAL AND MODE IMPUTATION\n')
dataset.info()
print(' ')
dataset.iloc[:,5]

CATEGORICAL AND MODE IMPUTATION

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29523 entries, 0 to 29522
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   record_id                     29523 non-null  object 
 1   utility_id_ferc1              29523 non-null  int64  
 2   report_year                   29523 non-null  int64  
 3   plant_name_ferc1              29523 non-null  object 
 4   fuel_type_code_pudl           29523 non-null  object 
 5   fuel_unit                     29343 non-null  object 
 6   fuel_qty_burned               29523 non-null  float64
 7   fuel_mmbtu_per_unit           29523 non-null  float64
 8   fuel_cost_per_unit_burned     29523 non-null  float64
 9   fuel_cost_per_unit_delivered  29523 non-null  float64
 10  fuel_cost_per_mmbtu           29523 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 2.5+ MB
 


0        ton
1        ton
2        ton
3        ton
4        mcf
        ... 
29518    mcf
29519    mcf
29520    mcf
29521    ton
29522    mcf
Name: fuel_unit, Length: 29523, dtype: object

<H2>QUESTION 8 </H2>

In [60]:
dataset.corr()

utility_id_ferc1  report_year  fuel_qty_burned  \
utility_id_ferc1                      1.000000     0.093323        -0.057447   
report_year                           0.093323     1.000000         0.012952   
fuel_qty_burned                      -0.057447     0.012952         1.000000   
fuel_mmbtu_per_unit                  -0.066946    -0.110853        -0.080946   
fuel_cost_per_unit_burned            -0.037863     0.013599        -0.018535   
fuel_cost_per_unit_delivered         -0.016414    -0.014043        -0.003551   
fuel_cost_per_mmbtu                   0.006122     0.010261        -0.001896   

                              fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
utility_id_ferc1                        -0.066946                  -0.037863   
report_year                             -0.110853                   0.013599   
fuel_qty_burned                         -0.080946                  -0.018535   
fuel_mmbtu_per_unit                      1.000000                  -0.010034   
fuel_cost_per_unit_burned               -0.010034                   1.000000   
fuel_cost_per_unit_delivered            -0.009039                   0.011007   
fuel_cost_per_mmbtu                     -0.005884                  -0.000437   

                              fuel_cost_per_unit_delivered  \
utility_id_ferc1                                 -0.016414   
report_year                                      -0.014043   
fuel_qty_burned                                  -0.003551   
fuel_mmbtu_per_unit                              -0.009039   
fuel_cost_per_unit_burned                         0.011007   
fuel_cost_per_unit_delivered                      1.000000   
fuel_cost_per_mmbtu                              -0.000109   

                              fuel_cost_per_mmbtu  
utility_id_ferc1                         0.006122  
report_year                              0.010261  
fuel_qty_burned                         -0.001896  
fuel_mmbtu_per_unit                     -0.005884  
fuel_cost_per_unit_burned               -0.000437  
fuel_cost_per_unit_delivered            -0.000109  
fuel_cost_per_mmbtu                      1.000000

<H2>QUESTION 9 </H2>

In [79]:
unit_type = (dataset.iloc[:,4] == 'coal')

record_year_1998 = (dataset.iloc[:,2] == 1998)
record_year_1994 = (dataset.iloc[:,2] == 1994)

con_1998 = dataset[record_year_1998 & unit_type]
con_1994 = dataset[record_year_1994 & unit_type]

sum_1998 = con_1998.iloc[:,8].sum()
sum_1994 = con_1994.iloc[:,8].sum()

diff = sum_1998 - sum_1994
result  = (diff/sum_1994)
result = result * 100
print('Difference in percent of 1998 to 1994 is: %.0f'%(result))

Difference in percent of 1998 to 1994 is: -21


<H2>QUESTION 10 </H2>

In [87]:
contents = dataset.iloc[:,2].unique()
result = {}

for content in contents:
    con = dataset.iloc[:,2] == content
    result[content] = dataset[con].iloc[:,9].mean()

result

{1994: 63.63605991902834,
 1995: 32.735268942547876,
 1996: 9196.705947610291,
 1997: 11140.197239488118,
 1998: 287.15442005420044,
 1999: 25.551626666666667,
 2000: 985.3628769118719,
 2001: 60.050396017699114,
 2002: 47.594360995850614,
 2003: 55.66349298100744,
 2004: 139.52427516778525,
 2005: 41.43818439716312,
 2006: 38.65748431214803,
 2007: 43.32502294303797,
 2008: 58.58819706840389,
 2009: 652.6941628477906,
 2010: 91.86210547184773,
 2011: 59.77466693548387,
 2012: 60.99450201126307,
 2013: 172.3075913261051,
 2014: 192.73718274978654,
 2015: 326.53551052150044,
 2016: 103.90176112185686,
 2017: 46.19686102719033,
 2018: 499.2699663512092}